name: Manually Update Image Tag
on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Name of the service to update'
        required: true
        type: string
      imageTag:
        description: 'Image tag to apply'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  Deploy-Image-Tag:
    environment:
      name: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate service name and image tag
        run: echo 'Ensuring no typos and image tag exists'
      - name: Update image tag
        run: |
          echo LEVEL: ${{ inputs.service }}
          echo TAGS: ${{ inputs.imageTag }}
          echo ENVIRONMENT: ${{ inputs.environment }}
